export default {
  MEETING_CREATED: 'MEETING_CREATED',
  MEETING_LENGTH_EDITED: 'MEETING_LENGTH_EDITED',
  MEETING_TIME_EDITED: 'MEETING_TIME_EDITED',
  MEETING_DAY_EDITED: 'MEETING_DAY_EDITED',
  MEETING_NAME_EDITED: 'MEETING_NAME_EDITED',
  MEETING_REMOVED: 'MEETING_REMOVED',
  MEETING_NOT_NEW_SET: 'MEETING_NOT_NEW_SET'
};
